# Generated by Django 4.1.7 on 2023-03-25 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewapp', '0002_alter_products_options_alter_categories_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='title',
            new_name='name',
        ),
    ]
